services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    ports:
      - "8085:8080"
    volumes:
      - /home/rory/homelab-data/glance/config:/app/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

