services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      - TZ=${TZ}

    volumes:
      - ${HOMELAB_DATA}/uptime-kuma:/app/data

