services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: "host"
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
      FTLCONF_webserver_port: "8081"
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - ${HOMELAB_DATA}/pihole/etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN

